apiVersion: sedna.io/v1alpha1
kind: MultiEdgeInferenceService
metadata:
  name: pedestrian-reid
  namespace: default
spec:
  inferenceWokers:
    -template:
      metadata:
        labels:
          app: reid-client
      spec:
        nodeName: "edge0"
        serviceAccountName: reid-client
        containers:
        - name: reid-client
          image: kubeedge/sedna-example-multi-edge-inference-reid-client:v0.1.0
          imagePullPolicy: IfNotPresent
          env: # user defined environments
            - name: "cameras"
              value: [192.168.0.10,192.168.0.11]
            - name: "modelUri"
              value: "http://103.124.124.134/RPpredictor_v1.0.tar.gz"
    -template:
      metadata:
        labels:
          app: reid-server
      spec:
        nodeSelector: 
        sedna/nodeRole: server
        serviceAccountName: reid-server
        containers:
        - name: reid-server
          image: kubeedge/sedna-example-multi-edge-inference-reid-server:v0.1.0
          env: # user defined environments
            - name: "detectorModelUri"
              value: "http://103.124.124.134/detector_v1.0.tar.gz"
            - name: "matcherModelUri"
              value: "http://103.124.124.134/matcher_v1.0.tar.gz"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
    -template:
      metadata:
        labels:
          app: reid-mqtt
      spec:
        containers:
        - name: reid-mqtt
          image: kubeedge/sedna-example-multi-edge-inference-reid-mqtt:v0.1.0
          imagePullPolicy: IfNotPresent
          ports:
          - name: dashbord
            containerPort: 18083
            protocol: TCP
          - name: mqtt
            containerPort: 1883
            protocol: TCP
  services:
    -template:
      metadata:
        name: reid-server
        labels:
          app: reid-server
      spec:
        ports:
        - name: http
          port: 3000
        selector:
          app: reid-server
    -template:
      metadata:
        name: reid-mqtt
        labels:
          app: reid-mqtt
      spec:
        ports:
        - name: dashbord
          protocol: TCP
          port: 18083
        - name: mqtt
          protocol: TCP
          port: 1883
        selector:
          app: reid-mqtt

      
